name: Create Branch and PR from Issue

on:
  issues:
    types: [opened]

env:
  branch_name: ""

permissions:
  contents: write

jobs:
  create-branch-and-pr:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Configure Git user
      run: |
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"

    - name: Create new branch
      id: create_branch
      run: |
        ISSUE_NUMBER=${{ github.event.issue.number }}
        ISSUE_TITLE="${{ github.event.issue.title }}"
        SANITIZED_TITLE=$(echo "${ISSUE_TITLE}" | tr -cd '[:alnum:]-' | tr '[:upper:]' '[:lower:]')
        BRANCH_NAME="issue-${ISSUE_NUMBER}-${SANITIZED_TITLE}"
        git checkout -b "$BRANCH_NAME"
        echo "branch_name=$BRANCH_NAME" >> $GITHUB_ENV

    - name: Verify branch context
      run: |
        echo "Current branch: $(git branch --show-current)"

    - name: Create markdown file from issue
      run: |
        ISSUE_NUMBER=${{ github.event.issue.number }}
        ISSUE_TITLE="${{ github.event.issue.title }}"
        ISSUE_BODY="${{ github.event.issue.body }}"
        echo "# ${ISSUE_TITLE}" > requests/request-test.md
        echo "${ISSUE_BODY}" >> requests/request-test.md
        git add .
        git commit -m "Add request #${ISSUE_NUMBER} as markdown file"
        git push origin ${{ env.branch_name }}

    - name: Create pull request
      uses: peter-evans/create-pull-request@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ env.branch_name }}
        title: "Add request #${{ github.event.issue.number }} as markdown file"
        body: "Salary sacrifice request #${{ github.event.issue.number }}."
        base: main