name: Create Branch and PR from Issue

on:
  issues:
    types: [opened]

env:
  branch_name: ""

permissions:
  contents: write

jobs:
  create-branch-and-pr:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Configure Git user
      run: |
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"

    - name: Create new branch
      id: create_branch
      run: |
        ISSUE_NUMBER=${{ github.event.issue.number }}
        ISSUE_TITLE="${{ github.event.issue.title }}"
        SANITIZED_TITLE=$(echo "${ISSUE_TITLE}" | tr -cd '[:alnum:]-' | tr '[:upper:]' '[:lower:]')
        BRANCH_NAME="issue-${ISSUE_NUMBER}-${SANITIZED_TITLE}"
        git checkout -b "$BRANCH_NAME"
        echo "branch_name=$BRANCH_NAME" >> $GITHUB_ENV

    - name: Create markdown file from issue
      run: |
        ISSUE_NUMBER=${{ github.event.issue.number }}
        ISSUE_TITLE="${{ github.event.issue.title }}"
        ISSUE_BODY="${{ github.event.issue.body }}"
        BRANCH_NAME="${{ env.branch_name }}"
        
        echo "Branch name: $BRANCH_NAME"
        echo "env var: ${{env.branch_name}}"
        
        echo "# ${ISSUE_TITLE}" > requests/request-${ISSUE_NUMBER}.md
        echo "${ISSUE_BODY}" >> requests/request-${ISSUE_NUMBER}.md
        
        git add .
        git commit -m "Add request #${ISSUE_NUMBER} as markdown file"
        git push --set-upstream origin ${BRANCH_NAME}